name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install gcovr
        run: sudo apt-get update && sudo apt-get install -y gcovr

      - name: Configure CMake with coverage
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_STANDARD=20 \
            -DCMAKE_CXX_FLAGS="--coverage" \
            -DCMAKE_EXE_LINKER_FLAGS="--coverage"

      - name: Build
        run: cmake --build build -j$(nproc)

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

      - name: Generate coverage report
        run: |
          gcovr -r . \
            --filter 'src/test_suite/test_suite\.cpp' \
            --filter 'src/assert/assert\.cpp' \
            --filter 'src/logging/logging\.cpp' \
            --filter 'src/test/test\.hpp' \
            --filter 'src/test_session/test_session\.hpp' \
            --filter 'src/fixture/fixture\.hpp' \
            --xml -o coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true

